version: "3"
services:
  nodejs-api:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/express--boilerplate
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    container_name: db_mongo
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    user: "1000:1000"
    ports:
      - "27017:27017"
    networks:
      - common
    restart: on-failure
networks:
    common: