exports.ErrorCodes = {
  ERROR_CODE_SUCCESS: 200,
  ERROR_CODE_INVALID_ARGUMENT: 400,
  ERROR_CODE_FORBIDDEN: 403,
  ERROR_CODE_NOT_FOUND: 404,
  ERROR_CODE_SUB_EXPRIED: 410,
  ERROR_CODE_SYSTEM_ERROR: 500,
};
